#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TURN_STATUS_OK 0
#define TURN_STATUS_OTHER_PLAYER 1
#define TURN_STATUS_INVALID_FUNCTION 2

#define FUNCTION_SHIFT_ROW_RIGHT 0
#define FUNCTION_SHIFT_ROW_LEFT 1
#define FUNCTION_SHIFT_COLUMN_DOWN 2
#define FUNCTION_SHIFT_COLUMN_UP 3
#define FUNCTION_QUIT_GAME 4

#endif // CONSTANTS_H